FROM php:7-apache
# postfix should run in a different container. not installed here.
# not configuring mysql here

RUN apt-get update &&\
    apt-get install -y libpng-dev libtidy-dev libicu-dev php-text-password bzr bzrtools &&\
    docker-php-ext-install -j$(nproc) gd tidy intl bcmath pdo_mysql opcache

RUN apt-get install -y uuid-dev &&\
    pecl install uuid apcu &&\
    docker-php-ext-enable uuid apcu

WORKDIR /usr/local/etc/php/conf.d/

RUN echo 'apc.enabled=1\n\
apc.write_lock=1\n\
apc.shm_size=100M\n\
apc.slam_defense=0\n\
apc.enable_cli=1\n'\
>> docker-php-ext-apcu.ini && cat docker-php-ext-apcu.ini

# php-memcached will not install, do this instead
RUN apt-get install -y libmemcached-dev zlib1g-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached

RUN echo 'opcache.memory_consumption=128M\n\
opcache.interned_strings_buffer=8\n\
opcache.max_accelerated_files=4000\n\
opcache.revalidate_freq=60\n\
opcache.fast_shutdown=1\n\
opcache.enable_cli=1\n'\
>> docker-php-ext-opcache.ini && cat docker-php-ext-opcache.ini

RUN a2enmod rewrite

WORKDIR /etc/apache2

RUN sed -i "s|Options Indexes FollowSymLinks|Options Indexes FollowSymLinks MultiViews|" apache2.conf && cat apache2.conf | grep Options

RUN mkdir -p /var/lib/iHRIS/lib/4.3-dev

WORKDIR /var/lib/iHRIS/lib/4.3-dev

RUN bzr co --lightweight lp:i2ce/4.3 I2CE &&\
    bzr co --lightweight lp:textlayout/4.3 textlayout &&\
    bzr co --lightweight lp:ihris-common/4.3 ihris-common &&\
    bzr co --lightweight lp:ihris-manage/4.3 ihris-manage

WORKDIR /var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/pages

RUN cp htaccess.TEMPLATE .htaccess &&\
    sed -i 's|RewriteBase  /iHRIS/manage-demo|RewriteBase /manage-demo|' .htaccess &&\
    cat .htaccess | grep manage &&\
    [ -d local ] || mkdir local

ARG DSN='mysql:user=ihris;pass=ihris;host=localhost;dbname=ihris'

RUN echo "<?php \n\
\$i2ce_site_i2ce_path = '/var/lib/iHRIS/lib/4.3-dev/I2CE' ;\n\
\$i2ce_site_dsn = $DSN ;\n\
\$i2ce_site_module_config = '/var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/iHRIS-Manage-Demo.xml' ;\n\
\$i2ce_site_user_access_init = null ;" >> local/config.values.php && cat local/config.values.php

WORKDIR /var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo

RUN printf '    <enable name="csd-data-address-type" />\n\
    <enable name="csd-data-dow" />\n\
    <enable name="csd-data-gender" />\n\
    <enable name="csd-data-provider-status" />\n\
    <enable name="csd-data-provider-data-model" />\n\
    <enable name="IL-HWR" />\n\
    <enable name="mHero" />\n\
    <enable name="csd-search" />\n\
    <enable name="CSD-data" />\n\
    ' >> enable.txt

RUN sed -i.bak '/<metadata>/r enable.txt' iHRIS-Manage-Demo.xml

WORKDIR /var/www/html

RUN ln -s /var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/pages manage-demo
