version: '3'

services:

  ihris-manage:
    build:
      context: .
      dockerfile: ./Dockerfile-manage
    ports:
      - "80:80"
    links:
      - mysql:mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "manage"
      MYSQL_DATABASE: "manage"
      MYSQL_USER: "manage"
      MYSQL_PASSWORD: "manage"
    command: mysqld --log-bin-trust-function-creators=TRUE --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
