FROM php:7-apache
# to troubleshoot, build then: docker run -it <image hash> bash

# postfix should run in a different container. not installed here.
# also not configuring mysql here

# installed in image but done anyway: mbstring, pdo
RUN php -i

RUN apt-get update &&\
    apt-get install -y libpng-dev libtidy-dev libicu-dev &&\
    docker-php-ext-install -j$(nproc) gd tidy intl bcmath pdo pdo_mysql opcache mbstring

RUN apt-get install -y php-pear && pear install text_password

RUN apt-get install -y uuid-dev &&\
    pecl install uuid apcu &&\
    docker-php-ext-enable uuid apcu

WORKDIR /usr/local/etc/php/conf.d/

# confirm apcu/uuid ini files in /usr/local/etc/php/conf.d/
RUN ls -l &&\
    cat docker-php-ext-uuid.ini

# configure apcu
RUN echo 'apc.enabled=1\n\
apc.write_lock=1\n\
apc.shm_size=100M\n\
apc.slam_defense=0\n\
apc.enable_cli=1\n'\
>> docker-php-ext-apcu.ini && cat docker-php-ext-apcu.ini

RUN apt-get install -y libmemcached-dev zlib1g-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached

RUN echo 'opcache.memory_consumption=128M\n\
opcache.interned_strings_buffer=8\n\
opcache.max_accelerated_files=4000\n\
opcache.revalidate_freq=60\n\
opcache.fast_shutdown=1\n\
opcache.enable_cli=1\n'\
>> docker-php-ext-opcache.ini && cat docker-php-ext-opcache.ini

RUN a2enmod rewrite

WORKDIR /etc/apache2

RUN sed -i "s|Options Indexes FollowSymLinks|Options Indexes FollowSymLinks MultiViews|" apache2.conf && cat apache2.conf

RUN apt-get install -y bzr bzrtools

RUN mkdir -p /var/lib/iHRIS/lib/4.3-dev

WORKDIR /var/lib/iHRIS/lib/4.3-dev

RUN bzr branch lp:i2ce/4.3 I2CE &&\
    bzr branch lp:textlayout/4.3 textlayout &&\
    bzr branch lp:ihris-common/4.3 ihris-common

RUN bzr branch lp:ihris-manage/4.3 ihris-manage

WORKDIR /var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/pages

RUN cp config.values.php local/ &&\
    cp htaccess.TEMPLATE .htaccess

RUN sed -i 's|"../../../../I2CE"|"/var/lib/iHRIS/lib/4.3-dev/I2CE"|' local/config.values.php &&\
    cat local/config.values.php | grep I2CE
# have to uncomment first for some reason
RUN sed -i 's|//$i2ce_site_dsn|$i2ce_site_dsn|' local/config.values.php &&\
    cat local/config.values.php | grep site_dsn
RUN sed -i "s|'mysql:user=john;pass=pass;host=localhost;dbname=database'|'mysql:user=manage;pass=manage;host=mysql;dbname=manage'|" local/config.values.php&&\
    cat local/config.values.php | grep mysql
RUN sed -i 's|//$i2ce_site_module_config = "MY_SITE_MODULE.xml"|$i2ce_site_module_config = "/var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/iHRIS-Manage-Demo.xml"|' local/config.values.php&&\
    cat local/config.values.php | grep xml

RUN sed -i 's|RewriteBase  /iHRIS/manage-demo|RewriteBase /manage-demo|' .htaccess &&\
    cat .htaccess

WORKDIR /var/www/html
RUN ln -s /var/lib/iHRIS/lib/4.3-dev/ihris-manage/sites/Demo/pages manage-demo
