version: '3'

services:

  ihris-manage-demo:
    image: ihris/manage:4.3-dev-0.2.0
    container_name: ihris
    ports:
      - "80:80"
    links:
      - mysql:mysql
    environment:
      DSN: "mysql:user=ihris;pass=ihris;host=mysql;dbname=ihris"

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "ihris"
      MYSQL_DATABASE: "ihris"
      MYSQL_USER: "ihris"
      MYSQL_PASSWORD: "ihris"
    command: mysqld --log-bin-trust-function-creators=TRUE --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
