version: '3'

services:

  ihris-manage-demo:
    image: ihris/manage:4.3.2-demo
    container_name: ihris
    ports:
      - "80:80"
    links:
      - mysql:mysql
      - memcached:memcached
    environment:
      DSN: "mysql:user=ihris;pass=ihris;host=mysql;dbname=ihris"
      IHRIS_MEMCACHED_SERVER: memcached

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ihris"
      MYSQL_DATABASE: "ihris"
      MYSQL_USER: "ihris"
      MYSQL_PASSWORD: "ihris"
    command: mysqld --log-bin-trust-function-creators=TRUE --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  memcached:
    image: memcached:alpine
    container_name: memcached